[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mantle = "https://rpc.sepolia.mantle.xyz" 

[etherscan]
mantle = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.mantlescan.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
